### PR TITLE
Upgrade to 1.7, cljx->cljc, cemerick.test->doo

### PR DESCRIPTION
**Pull request by bensu**
After upgrading to clojure 1.7 to use reader conditionals, cljsbuild
needed to be updated to its latest version, and cemerick.test replaced
by cljs.test to set the tests + lein-doo to run the tests.

### CODE REVIEW

**Comment by bensu** [comment]
I apologize for the extra commits! It's hard to test Travis locally :) When I correct Travis CI I'll squash the commits and make another PR.

Also, let me know if/where you want me to add a Change notice.

**Comment by bensu** [comment]
lein 2.5.1 doesn't recognize cljc files when running tests. I'm trying to configure Travis to use lein 2.5.2 which fixed the issue (see https://github.com/technomancy/leiningen/issues/1940 for more info).

**Comment by qerub** [comment]
Thanks! :bow: 

.

> When I correct Travis CI I'll squash the commits and make another PR.

You don't have to make another PR; just change what commit `bensu:cljc` points to.

> Also, let me know if/where you want me to add a Change notice.

I'll take care of updating `NEWS.md`. I'll also add you to `AUTHORS.md`.

.

Cleanup the commit history and I'll merge. See if you can request the merge to be against `master` instead of `stable` too.

**Comment by stoyle** [comment]
Is this complete, or do you need help getting it complete?

We'd very much like to use the camel-snake-kebab for our ClojureScript app, but would like to avoid the cljx overhead.

**Comment by qerub** [comment]
@stoyle AFAIK it is complete. Thanks for the poke. I'll get it merged this weekend!

**Comment by stoyle** [comment]
Cool, thanks!

**Comment by qerub** [comment]
Squashed and merged in 90edf7e98bef29e6ad8a7c7e67adfebfef636cf5.

**Comment by qerub** [comment]
@stoyle Can you give the 0.4.0-SNAPSHOT build on Clojars a spin?

**Comment by stoyle** [comment]
Works great! Included it into our app, and works as expected.

Also done a `->kebab-case-keyword` and back to `->camelCaseString`, starting point and result ends up being equal.

**Comment by qerub** [comment]
@stoyle Thanks! I'll do a proper release during the weekend and notify you.

**Comment by qerub** [comment]
@stoyle It is done: https://clojars.org/camel-snake-kebab/versions/0.4.0

**Comment by stoyle** [comment]
Thanks!

**Pull request closed without merging**
